version: '3.9'
services:
  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "${HOST_PORT:?}:80"
    volumes:
      - ./nginx_templates:/etc/nginx/templates
      - ${NGINX_PUBLIC_DIR:?}:/public
      - ${NGINX_LOG_DIR:?}:/logs
    environment:
      - NGINX_ENVSUBST_TEMPLATE_SUFFIX=.nginx

  cloudflared:
    image: cloudflare/cloudflared:latest
    command: tunnel run
    restart: always
    depends_on:
      - nginx
    environment:
      TUNNEL_TOKEN: ${CLOUDFLARED_TUNNEL_TOKEN:?}
